name: Prelive Branch Protection

on:
  pull_request:
    branches:
      - "prelive"

permissions:
  contents: read

jobs:
  validate-source:
    uses: montonio/github-actions/.github/workflows/branch-protection.yml@main
    with:
      target-branch: "prelive"
      allowed-source-branches: "develop"
